FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONDONTWRITEBYTECODE 1
ENV PATH $PATH:/opt/rocm/bin:/opt/rocm/opencl/bin
ENV HSA_USERPTR_FOR_PAGED_MEM=0
ENV TF_ROCM_FUSION_ENABLE 1
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/opt/rocm/lib:$LD_LIBRARY_PATH

RUN env > /etc/environment

RUN apt-get update && apt install -y --no-install-recommends git ca-certificates \
    vim-tiny less netcat-openbsd inetutils-ping curl patch iproute2 \
    g++ libpci3 libnuma-dev make file openssh-server kmod gdb libopenmpi-dev openmpi-bin psmisc \
        autoconf automake autotools-dev libtool \
        zlib1g-dev rename zip unzip librdmacm-dev gnupg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN curl -L https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add -
RUN printf "deb [arch=amd64] http://repo.radeon.com/rocm/apt/6.3.3/ ubuntu main" | tee /etc/apt/sources.list.d/rocm_hip.list && \
    apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    rocm-dev rocblas hipblas-dev hipsparse rccl rocfft hipfft rocrand miopen-hip rocthrust hip-rocclr hipsparse-dev rccl-dev rocblas-dev hipblaslt-dev hipsolver-dev && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN /bin/echo -e "set backspace=indent,eol,start\nset nocompatible\nset ts=4" > /etc/vim/vimrc.tiny

RUN curl -L https://github.com/python-for-ubuntu/python3.12/releases/download/release/python3.12-linux-$(uname -m).deb -o /tmp/setup.deb && apt install -y /tmp/setup.deb && rm -f /tmp/setup.deb

RUN ln -sf $(which python3.12) /usr/bin/python3
RUN ln -sf $(which pip3.12) /usr/bin/pip3
RUN ln -sf python3 /usr/bin/python
RUN ln -sf python /usr/bin/python.exe
RUN ln -sf pip3 /usr/bin/pip

RUN python3 -m pip install --upgrade antares && mkdir -p /root/.local/antares && mv $(antares pwd)/../3rdparty /root/.local/antares/3rdparty && pip3 uninstall antares -y && echo 'exec /antares/main.py "$@"' > /usr/local/bin/antares && chmod a+x /usr/local/bin/antares

# OpenCL has been included in ROCm already
RUN rm -rf /usr/lib/x86_64-linux-gnu/libOpenCL.so.1*

RUN python3 -m pip install torch networkx --index-url https://download.pytorch.org/whl/rocm6.2.4
# RUN python3 -m pip install -v --no-build-isolation git+https://github.com/microsoft/tutel@main
RUN python3 -m pip install -U "huggingface_hub[cli]" transformers
