FROM intel/oneapi-hpckit:2023.2.1-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONDONTWRITEBYTECODE 1

RUN env > /etc/environment

RUN sed -i 's/^#deb /deb /g' /etc/apt/sources.list
RUN rm -rf /etc/apt/sources.list.d/*

RUN apt-get update && apt install -y --no-install-recommends git ca-certificates \
    vim-tiny less netcat-openbsd inetutils-ping curl patch iproute2 \
    g++ libpci3 libnuma-dev make file openssh-server kmod gdb psmisc \
        autoconf automake autotools-dev libtool \
        zlib1g-dev rename zip unzip librdmacm-dev gnupg p7zip-full rsync \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN /bin/echo -e "set backspace=indent,eol,start\nset nocompatible\nset ts=4" > /etc/vim/vimrc.tiny
RUN cp -r /opt/intel/oneapi/compiler/latest/linux/include/sycl/CL /opt/intel/oneapi/compiler/latest/linux/include/

RUN curl -L https://github.com/python-for-ubuntu/python3.12/releases/download/release/python3.12-linux-$(uname -m).deb -o /tmp/py.deb && dpkg -i /tmp/py.deb && rm -f /tmp/py.deb
RUN ln -sf /usr/local/bin/python3.12 /usr/local/bin/python3
RUN ln -sf python3 /usr/local/bin/python
RUN ln -sf python /usr/local/bin/python.exe
RUN /bin/echo -e 'exec python3 -m pip "$@"' > /usr/local/bin/pip3 && chmod a+x /usr/local/bin/pip3
RUN ln -sf pip3 /usr/local/bin/pip

RUN pip3 install --upgrade antares && mkdir -p /root/.local/antares && mv $(antares pwd)/../3rdparty /root/.local/antares/3rdparty && pip3 uninstall antares -y && echo 'exec /antares/main.py "$@"' > /usr/local/bin/antares && chmod a+x /usr/local/bin/antares

RUN python3 -m pip install cython setuptools
RUN python3 -m pip install https://download.pytorch.org/whl/cpu/torch-2.2.0%2Bcpu-cp312-cp312-linux_x86_64.whl
RUN python3 -m pip install https://download.pytorch.org/whl/cpu/torchaudio-2.2.0%2Bcpu-cp312-cp312-linux_x86_64.whl
RUN python3 -m pip install https://download.pytorch.org/whl/cpu/torchvision-0.17.0%2Bcpu-cp312-cp312-linux_x86_64.whl

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg
