FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
# FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONDONTWRITEBYTECODE 1
ENV PATH $PATH:/usr/local/nvidia/lib64/bin
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda/compat:$LD_LIBRARY_PATH

RUN env > /etc/environment

RUN apt-get update && apt install -y --no-install-recommends git ca-certificates \
    vim-tiny less netcat-openbsd inetutils-ping curl patch iproute2 \
    g++ libpci3 libnuma-dev make file openssh-server kmod gdb libopenmpi-dev openmpi-bin psmisc \
        autoconf automake autotools-dev libtool \
        zlib1g-dev rename zip unzip librdmacm-dev gnupg p7zip-full sudo rsync zstd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# RUN apt-get update && apt install -y --no-install-recommends python3-distutils python3-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN curl -LO https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm -f get-pip.py
RUN curl -L https://github.com/python-for-ubuntu/python3.12/releases/download/release/python3.12-linux-$(uname -m).deb -o /tmp/setup.deb && apt install -y /tmp/setup.deb && rm -f /tmp/setup.deb

RUN ln -sf $(which python3.12) /usr/bin/python3
RUN ln -sf $(which pip3.12) /usr/bin/pip3
RUN ln -sf python3 /usr/bin/python
RUN ln -sf python /usr/bin/python.exe
RUN ln -sf pip3 /usr/bin/pip

RUN /bin/echo -e "set backspace=indent,eol,start\nset nocompatible\nset ts=4" > /etc/vim/vimrc.tiny

RUN pip3 install --upgrade antares>=0.3.25.1 && mkdir -p /root/.local/antares && \
    mv $(antares pwd)/../3rdparty /root/.local/antares/3rdparty && pip3 uninstall antares -y && \
    echo 'exec /antares/main.py "$@"' > /usr/local/bin/antares && chmod a+x /usr/local/bin/antares

RUN [ -e /usr/lib/x86_64-linux-gnu/libcuda.so.1 ] || ln -s /host/usr/lib/x86_64-linux-gnu/libcuda.so.1 /usr/lib/x86_64-linux-gnu
# RUN ln -sf libcudart.so /usr/local/cuda/targets/x86_64-linux/lib/libcudart_static.a

ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib64:$LD_LIBRARY_PATH

RUN python3 -m pip install cython setuptools
RUN python3 -m pip install torch torchaudio torchvision --index-url https://download.pytorch.org/whl/cu118
RUN python3 -m pip install -U "huggingface_hub[cli]"
RUN python3 -m pip install git+https://github.com/microsoft/tutel@main
RUN python3 -m pip install https://github.com/microsoft/antares/releases/download/v0.9.6/autort-0.9.6.3.8+cuda.zip

# RUN mkdir -p /usr/local/nvidia/bin/ && /bin/echo 'sudo /usr/local/cuda/bin/nsys profile --stats=true -o /tmp/ "$@"' > /usr/local/nvidia/bin/nvprof && chmod a+x /usr/local/nvidia/bin/nvprof
